name: CMake

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  CXX_FLAGS: "-std=c++17 -Wall -pedantic -Werror -Wno-variadic-macros -Wno-long-long -Wno-shadow"

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install libglu1-mesa-dev freeglut3-dev mesa-common-dev libudev-dev libvorbis-dev libflac-dev libopenal-dev libfreetype6-dev libx11-dev libxrandr-dev libxcursor-dev
    
    - name: Install SFML
      run: git clone https://github.com/SFML/SFML --branch master && cd SFML && git checkout ef8fee53567af3e47026f6485164d4f95a2be5da && cmake . && make && sudo mv include/* /usr/include/ && sudo mv lib/* /usr/lib/

    - name: Install TGUI
      run: cd .. && git clone https://github.com/texus/TGUI --branch 0.8 && cd TGUI && cmake . && make -j2 && sudo make install && cd ..

    - name: Build and run tests
      # Build your program with the given configuration
      run: ./build_and_run_tests.bash
